bind9:
  extends:
    file: base.yml
    service: bind9
  volumes:
    - "/srv/bind9/cache:/var/cache/bind"
    - "/srv/bind9/lib:/var/lib/bind"
    - "/srv/bind9/named.conf.options:/etc/bind/named.conf.options"
    - "/srv/bind9/named.conf.local:/etc/bind/named.conf.local"
